<h3 class="manga">Manga</h3>
<a class="manga">ABCDEFGHIJKLMNÑOPQRSTUVWXYZ<br>abcdefghijklmnñopqrstuvwxyz<br>|1234567890'¿!"#$%&/()=?¡´+{}¨*[],.-;:_\~^`</a><br>
<h3 class="kioshima">Kioshima</h3>
<a class="kioshima">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>abcdefghijklmnopqrstuvwxyz<br>|1234567890!#$%&/()=?+{}*[]-_\~^</a><br>
<h3 class="gui">GUI</h3>
<a class="gui">ADSW<br>abcdgiopqsvwxz<br>|1234567890'!"#$%&/()=?+{}*[],.-;:_\^</a><br>
<h3 class="">ICO</h3>
<a class="ico">ABCDEFGHIJKLMNÑOPQRSTUVWXYZ<br>abcdefghijklmnñopqrstuvwxyz<br>|1234567890'!"#$%&/()=?+{}¨*[],.-;:_¬\~^`</a><br>
<h3 class="cubic">Cubic</h3>
<a class="cubic">ABCDEFGHIJKLMNÑOPQRSTUVWXYZ<br>abcdefghijklmnñopqrstuvwxyz<br>1234567890¿!"#$&()=?¡´*[],.-;:^`</a><br>
<h3 class="TECHNOH">TECHNOH</h3>
<a class="TECHNOH">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>abcdefghijklmnopqrstuvwxyz<br>|1234567890'!"()?{}[],.;:_~</a><br>
<h3 class="cube">CUBEcube</h3>
<a class="cube">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>abcdefghijklmnopqrstuvwxyz<br>123456789!?</a><br>
<h3 class="hexagon">HEXAGONhexagon</h3>
<a class="hexagon">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>abcdefghijklmnopqrstuvwxyz</a><br>
<h3 class="simple">SIMPLE</h3>
<a class="simple">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>abcdefghijklmnopqrstuvwxyz<br>1234567890!%/()?+[],.;:</a><br>
<h3 class="over">OVERover</h3>
<a class="over">ABCDEFGHIJKLMNÑOPQRSTUVWXYZ<br>abcdefghijklmnñopqrstuvwxyz<br>|1234567890'¿°!"#$%&/()=?¡´+{}*[],.-;:_\^`</a><br>
<h3 class="">Heydings</h3>
<a class="heydings">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>abcdefghiklmnopqrstuvwy<br>123458!+*-</a><br>
<h3 class="mine1">MINECRAFT</h3>
<a class="mine1">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>abcdefghijklmnopqrstuvwxyz<br>1234567890</a><br>
<h3 class="">Eyes</h3>
<a class="eyes">ABCDEFGHIJKLMNOPQ<br>RSTUVWXYZ1234567890</a><br>